In [1]:
import pandas as pd
import numpy as np

In [6]:
df1 = pd.read_csv("./서울시 상권분석서비스(영역-상권).csv", encoding='cp949')
df1

,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,엑스좌표_값,와이좌표_값,자치구_코드,자치구_코드_명,행정동_코드,행정동_코드_명,영역_면적
0,A,골목상권,3110008,배화여자대학교(박노수미술관),197093,453418,11110,종로구,11110515,청운효자동,149264
1,A,골목상권,3110009,자하문터널,196991,455057,11110,종로구,11110550,부암동,178306
2,A,골목상권,3110010,평창동서측,197064,456643,11110,종로구,11110560,평창동,369415
3,A,골목상권,3110017,정독도서관,198581,453781,11110,종로구,11110600,가회동,83855
4,A,골목상권,3110018,중앙고등학교,198883,453690,11110,종로구,11110600,가회동,166872
...,...,...,...,...,...,...,...,...,...,...,...
1645,U,관광특구,3001492,명동 남대문 북창동 다동 무교동 관광특구,198397,451614,11140,중구,11140520,소공동,983618
1646,U,관광특구,3001493,동대문패션타운 관광특구,200996,451976,11140,중구,11140590,광희동,606058
1647,U,관광특구,3001494,종로?청계 관광특구,199796,452274,11110,종로구,11110615,종로1?2?3?4가동,653127
1648,U,관광특구,3001495,잠실 관광특구,210188,446334,11710,송파구,11710562,방이2동,2462734
1649,U,관광특구,3001496,강남 마이스 관광특구,205282,445736,11680,강남구,11680580,삼성1동,237892

In [7]:
df2 = pd.read_csv("./서울시 상권분석서비스(점포-상권).csv", encoding="cp949")
df2

,기준_년분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,점포_수,유사_업종_점포_수,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수
0,20252,R,전통시장,3130327,"평화시장(남평화시장, 제일평화시장, 신평화패션타운)",CS300043,전자상거래업,4,4,0,0,0,0,0
1,20252,R,전통시장,3130327,"평화시장(남평화시장, 제일평화시장, 신평화패션타운)",CS300035,인테리어,2,2,0,0,0,0,0
2,20252,R,전통시장,3130327,"평화시장(남평화시장, 제일평화시장, 신평화패션타운)",CS300029,애완동물,1,1,0,0,0,0,0
3,20252,R,전통시장,3130327,"평화시장(남평화시장, 제일평화시장, 신평화패션타운)",CS300027,섬유제품,2,2,0,0,0,0,0
4,20252,R,전통시장,3130327,"평화시장(남평화시장, 제일평화시장, 신평화패션타운)",CS300024,운동/경기용품,5,5,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459505,20241,U,관광특구,3001491,이태원 관광특구,CS100005,제과점,25,30,0,0,0,0,5
459506,20241,U,관광특구,3001491,이태원 관광특구,CS100004,양식음식점,221,226,2,5,2,5,5
459507,20241,U,관광특구,3001491,이태원 관광특구,CS100003,일식음식점,24,25,0,0,0,0,1
459508,20241,U,관광특구,3001491,이태원 관광특구,CS100002,중식음식점,17,19,0,0,0,0,2
459509,20241,U,관광특구,3001491,이태원 관광특구,CS100001,한식음식점,122,134,8,10,3,4,12

In [10]:
df1.columns

Index(['상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명', '엑스좌표_값', '와이좌표_값',
       '자치구_코드', '자치구_코드_명', '행정동_코드', '행정동_코드_명', '영역_면적'],
      dtype='object')

In [11]:
df2.columns

Index(['기준_년분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명', '서비스_업종_코드',
       '서비스_업종_코드_명', '점포_수', '유사_업종_점포_수', '개업_율', '개업_점포_수', '폐업_률',
       '폐업_점포_수', '프랜차이즈_점포_수'],
      dtype='object')